baseURL = "http://localhost/hpc-esb/"
publishDir = "private"
buildDrafts = true
title = "Metal — HPC cluster of ESB, SOKENDAI"
theme = "hugo-theme-nonblog"
languageCode = "ja"
hasCJKLanguage = true
noTimes = true
disableKinds = ["RSS"]
pygmentsCodefences = true
pygmentsUseClasses = true

[author]
name = "Watal M. Iwasaki"

[markup.goldmark.renderer]
unsafe = true

[params]
logo_src = "sokendai-logomark.svg"
logo_alt = "sokendai-logomark.svg"
theme_color = "#1a4694"
