sudo: false
language: generic
branches:
  only:
  - public
notifications:
  email: false
  slack:
    secure: Fm0fyPT/4M3uKANR2qkn+ZBn8X/2SWlU72qXGVBKNTfolF6CXrWmFZG82rzpqrs5j/scpMcRu8gGYvcq7L+rnGCV2XvKM/PrYFy9534wXO6FuSQvIjvT1l2D9KJaYgHB1NAZynvVZwZnCJ5G+CJbHOWUrSJBI66RPXr4C2ysnnLfE8NSkcBQz5GK3RVAA5khG8035zLwMTRO8KMC56F71e28TKZyqYUbWh2EbvLoo/fdQe4OPmYnqWTveKhizsb1uLQjkwMQYo4rf+ouuM1v/K3UTt661ayjLgzQbFOJisQoAvlNmUHr9+Cnv9fMP1SDE5pWfT80wIZ42b6x9gS3+3w3Rnimj3K929ePgTtMppRrVKkaRvkCSmlVvgyrCilEIUuv6KR+i5fh7uBUOukCD2ZD7GLxq5fwua65fqqplXkt6kqa6V6+5LfcTHldal6+LixzcDtMTiCKFJaGnblm+bR4dhXZScRK976QrW7ViLjl0QuOjg6RZa8wCJ9hnvqb7paJnB7Img0HRnDCkBaTzvaPQvyclDrCmBVFM6CEDzZ8WDhK5X6elfRkwIG4mN6phhra7yFOqqQ0snI6afm/2g2Ja69URIU0Hqs1rCY9zuTS17PMTN5v1LgqzB2/p/RlR0va4vHtD50HpFXVTHkulgDeJA875PfU96MwJ+/0Sr8=
