baseURL = "http://localhost/restricted_access/esb-hpc/"
publishDir = "../heavywatal.github.io/public/restricted_access/esb-hpc/"
title = "Metal — HPC cluster of ESB, SOKENDAI"
theme = "nonblog"
languageCode = "ja"
hasCJKLanguage = true
noTimes = true
disableKinds = ["RSS"]
pygmentsCodefences = true
pygmentsUseClasses = true

[author]
name = "Watal M. Iwasaki"

[blackfriday]
fractions = false
plainIDAnchors = true

[params]
logo_src = "sokendai-logomark.svg"
logo_alt = "sokendai-logomark.svg"
theme_color = "#1a4694"
