baseURL = "http://localhost/esb-hpc/"
publishDir = "../heavywatal.github.io/public/esb-hpc/"
title = "Metal — HPC cluster of ESB, SOKENDAI"
theme = "nonblog"
languageCode = "ja"
hasCJKLanguage = true
noTimes = true
disableKinds = ["RSS"]
pygmentsCodefences = true
pygmentsUseClasses = true

[blackfriday]
fractions = false
plainIDAnchors = true

[params]
logo_src = "sokendai-logo.png"
logo_alt = "sokendai-logo.png"
