baseURL = "http://localhost/restricted_access/esb-hpc/"
publishDir = "../heavywatal.github.io/public/restricted_access/esb-hpc/"
title = "Metal — HPC cluster of ESB, SOKENDAI"
theme = "nonblog"
languageCode = "ja"
hasCJKLanguage = true
noTimes = true
disableKinds = ["RSS"]
pygmentsCodefences = true
pygmentsUseClasses = true

[author]
name = "Watal M. Iwasaki"

[blackfriday]
fractions = false
plainIDAnchors = true

[params]
logo_src = "android-chrome-192x192.png"
logo_alt = "android-chrome-192x192.png"
theme_color = "#1a4694"
